### ISSUE TITLE
Canvas Reset Button

### ISSUE THREAD

**Issue by SpiritSeal** [SpiritSeal/bubblemap#56]
Button to reset canvas pan and zoom back to default, in the event a user gets lost.

**Comment by SpiritSeal** [comment]
I'll add the DOM element at some point. @epodol, you'll just prob be responsible for binding the onClick handler I'll expose to an actual function that can reset the pan and zoom, which I think already `resetTransform()` function from `react-zoom-pan-pinch`.

**Comment by epodol** [comment]
Here is some code we can use if we need to:

```typescript
    const { contentComponent, wrapperComponent } = context.instance;
    const { scale } = context.state;

    const contentWidth = (contentComponent?.offsetWidth ?? 0) * scale;
    const contentHeight = (contentComponent?.offsetHeight ?? 0) * scale;

    const centerPositionX =
      ((wrapperComponent?.offsetWidth ?? 0) - contentWidth) / 2;
    const centerPositionY =
      ((wrapperComponent?.offsetHeight ?? 0) - contentHeight) / 2;
```
